//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kurssovay_1.Bases
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class SellVouchersEntities4 : DbContext
    {
        private static SellVouchersEntities4 _context;
        public SellVouchersEntities4()
            : base("name=SellVouchersEntities4")
        {
        }
        public static SellVouchersEntities4 GetContext()
        {
            if (_context == null)
                _context = new SellVouchersEntities4();
            return _context;

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Cabins> Cabins { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Cruises> Cruises { get; set; }
        public virtual DbSet<Ships> Ships { get; set; }
        public virtual DbSet<Vouchers> Vouchers { get; set; }
    }
}
