//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kurssovay_1.Bases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vouchers
    {
        public int id_vouchers { get; set; }
        public int id_clients { get; set; }
        public int id_cruises { get; set; }
        public int id_cabins { get; set; }
        public int id_ships { get; set; }

        public string ShipName
        {
            get
            {
                return Cruises.Ships.name_ships;
            }
        }

        public virtual Cabins Cabins { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Cruises Cruises { get; set; }
    }
}
